# Generated by Django 5.0.1 on 2024-02-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfile',
            name='image',
            field=models.ImageField(upload_to='uploaded_imgs/'),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='converted_pdfs/'),
        ),
    ]
